# Generated by Django 3.1 on 2020-12-25 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_about_food', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('rating', models.IntegerField()),
                ('category', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='restaurent',
            name='category',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='restaurent',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='restaurent',
            name='image',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='restaurent',
            name='rating',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='restaurent',
            name='address',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='restaurent',
            name='Dishes',
            field=models.ManyToManyField(default=None, to='all_about_food.Dish'),
        ),
    ]
