# Generated by Django 3.1 on 2020-12-25 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_about_food', '0004_auto_20201225_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(upload_to='all_about/food/static/img/dishes'),
        ),
        migrations.AlterField(
            model_name='restaurent',
            name='image',
            field=models.ImageField(upload_to='all_about/food/static/img/restaurents'),
        ),
    ]
