# Generated by Django 3.1 on 2020-12-25 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_about_food', '0005_auto_20201225_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='rating',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='restaurent',
            name='rating',
            field=models.CharField(max_length=5),
        ),
    ]
