# Generated by Django 3.1 on 2020-12-25 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_about_food', '0008_auto_20201226_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='image_url',
            field=models.CharField(default='sd', max_length=150),
        ),
    ]
