# Generated by Django 3.1 on 2020-12-25 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_about_food', '0009_dish_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurent',
            name='image_url',
            field=models.CharField(default='sd', max_length=150),
        ),
    ]
